// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bazueva/metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreateMetric provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateMetric(metricType string, name string, value string) (models.Metrics, error) {
	ret := _mock.Called(metricType, name, value)

	if len(ret) == 0 {
		panic("no return value specified for CreateMetric")
	}

	var r0 models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (models.Metrics, error)); ok {
		return returnFunc(metricType, name, value)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) models.Metrics); ok {
		r0 = returnFunc(metricType, name, value)
	} else {
		r0 = ret.Get(0).(models.Metrics)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(metricType, name, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMetric'
type MockStorage_CreateMetric_Call struct {
	*mock.Call
}

// CreateMetric is a helper method to define mock.On call
//   - metricType string
//   - name string
//   - value string
func (_e *MockStorage_Expecter) CreateMetric(metricType any, name any, value any) *MockStorage_CreateMetric_Call {
	return &MockStorage_CreateMetric_Call{Call: _e.mock.On("CreateMetric", metricType, name, value)}
}

func (_c *MockStorage_CreateMetric_Call) Run(run func(metricType string, name string, value string)) *MockStorage_CreateMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_CreateMetric_Call) Return(metrics models.Metrics, err error) *MockStorage_CreateMetric_Call {
	_c.Call.Return(metrics, err)
	return _c
}

func (_c *MockStorage_CreateMetric_Call) RunAndReturn(run func(metricType string, name string, value string) (models.Metrics, error)) *MockStorage_CreateMetric_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMetrics provides a mock function for the type MockStorage
func (_mock *MockStorage) GetAllMetrics() []models.Metrics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 []models.Metrics
	if returnFunc, ok := ret.Get(0).(func() []models.Metrics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}
	return r0
}

// MockStorage_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockStorage_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
func (_e *MockStorage_Expecter) GetAllMetrics() *MockStorage_GetAllMetrics_Call {
	return &MockStorage_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics")}
}

func (_c *MockStorage_GetAllMetrics_Call) Run(run func()) *MockStorage_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_GetAllMetrics_Call) Return(metricss []models.Metrics) *MockStorage_GetAllMetrics_Call {
	_c.Call.Return(metricss)
	return _c
}

func (_c *MockStorage_GetAllMetrics_Call) RunAndReturn(run func() []models.Metrics) *MockStorage_GetAllMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetric provides a mock function for the type MockStorage
func (_mock *MockStorage) GetMetric(name string) (models.Metrics, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetMetric")
	}

	var r0 models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.Metrics, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.Metrics); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(models.Metrics)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type MockStorage_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - name string
func (_e *MockStorage_Expecter) GetMetric(name any) *MockStorage_GetMetric_Call {
	return &MockStorage_GetMetric_Call{Call: _e.mock.On("GetMetric", name)}
}

func (_c *MockStorage_GetMetric_Call) Run(run func(name string)) *MockStorage_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_GetMetric_Call) Return(metrics models.Metrics, err error) *MockStorage_GetMetric_Call {
	_c.Call.Return(metrics, err)
	return _c
}

func (_c *MockStorage_GetMetric_Call) RunAndReturn(run func(name string) (models.Metrics, error)) *MockStorage_GetMetric_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetric provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateMetric(metric models.Metrics) error {
	ret := _mock.Called(metric)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetric")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Metrics) error); ok {
		r0 = returnFunc(metric)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_UpdateMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetric'
type MockStorage_UpdateMetric_Call struct {
	*mock.Call
}

// UpdateMetric is a helper method to define mock.On call
//   - metric models.Metrics
func (_e *MockStorage_Expecter) UpdateMetric(metric any) *MockStorage_UpdateMetric_Call {
	return &MockStorage_UpdateMetric_Call{Call: _e.mock.On("UpdateMetric", metric)}
}

func (_c *MockStorage_UpdateMetric_Call) Run(run func(metric models.Metrics)) *MockStorage_UpdateMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Metrics
		if args[0] != nil {
			arg0 = args[0].(models.Metrics)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateMetric_Call) Return(err error) *MockStorage_UpdateMetric_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_UpdateMetric_Call) RunAndReturn(run func(metric models.Metrics) error) *MockStorage_UpdateMetric_Call {
	_c.Call.Return(run)
	return _c
}
