// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bazueva/metrics/internal/notifier/events"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Notify(event events.MetricsSavedEvent) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(events.MetricsSavedEvent) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - event events.MetricsSavedEvent
func (_e *MockNotifier_Expecter) Notify(event any) *MockNotifier_Notify_Call {
	return &MockNotifier_Notify_Call{Call: _e.mock.On("Notify", event)}
}

func (_c *MockNotifier_Notify_Call) Run(run func(event events.MetricsSavedEvent)) *MockNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 events.MetricsSavedEvent
		if args[0] != nil {
			arg0 = args[0].(events.MetricsSavedEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_Notify_Call) Return(err error) *MockNotifier_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifier_Notify_Call) RunAndReturn(run func(event events.MetricsSavedEvent) error) *MockNotifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}
