// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bazueva/metrics/internal/notifier"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriber creates a new instance of MockSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriber {
	mock := &MockSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriber is an autogenerated mock type for the Subscriber type
type MockSubscriber struct {
	mock.Mock
}

type MockSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriber) EXPECT() *MockSubscriber_Expecter {
	return &MockSubscriber_Expecter{mock: &_m.Mock}
}

// OnMetricsSaved provides a mock function for the type MockSubscriber
func (_mock *MockSubscriber) OnMetricsSaved(event notifier.MetricsSavedEvent) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for OnMetricsSaved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(notifier.MetricsSavedEvent) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriber_OnMetricsSaved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnMetricsSaved'
type MockSubscriber_OnMetricsSaved_Call struct {
	*mock.Call
}

// OnMetricsSaved is a helper method to define mock.On call
//   - event notifier.MetricsSavedEvent
func (_e *MockSubscriber_Expecter) OnMetricsSaved(event any) *MockSubscriber_OnMetricsSaved_Call {
	return &MockSubscriber_OnMetricsSaved_Call{Call: _e.mock.On("OnMetricsSaved", event)}
}

func (_c *MockSubscriber_OnMetricsSaved_Call) Run(run func(event notifier.MetricsSavedEvent)) *MockSubscriber_OnMetricsSaved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 notifier.MetricsSavedEvent
		if args[0] != nil {
			arg0 = args[0].(notifier.MetricsSavedEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubscriber_OnMetricsSaved_Call) Return(err error) *MockSubscriber_OnMetricsSaved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriber_OnMetricsSaved_Call) RunAndReturn(run func(event notifier.MetricsSavedEvent) error) *MockSubscriber_OnMetricsSaved_Call {
	_c.Call.Return(run)
	return _c
}
