// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bazueva/metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollector creates a new instance of MockCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollector {
	mock := &MockCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollector is an autogenerated mock type for the Collector type
type MockCollector struct {
	mock.Mock
}

type MockCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollector) EXPECT() *MockCollector_Expecter {
	return &MockCollector_Expecter{mock: &_m.Mock}
}

// ExtendedMetricSnapshot provides a mock function for the type MockCollector
func (_mock *MockCollector) ExtendedMetricSnapshot() ([]models.Metrics, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExtendedMetricSnapshot")
	}

	var r0 []models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Metrics, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Metrics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollector_ExtendedMetricSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendedMetricSnapshot'
type MockCollector_ExtendedMetricSnapshot_Call struct {
	*mock.Call
}

// ExtendedMetricSnapshot is a helper method to define mock.On call
func (_e *MockCollector_Expecter) ExtendedMetricSnapshot() *MockCollector_ExtendedMetricSnapshot_Call {
	return &MockCollector_ExtendedMetricSnapshot_Call{Call: _e.mock.On("ExtendedMetricSnapshot")}
}

func (_c *MockCollector_ExtendedMetricSnapshot_Call) Run(run func()) *MockCollector_ExtendedMetricSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollector_ExtendedMetricSnapshot_Call) Return(metricss []models.Metrics, err error) *MockCollector_ExtendedMetricSnapshot_Call {
	_c.Call.Return(metricss, err)
	return _c
}

func (_c *MockCollector_ExtendedMetricSnapshot_Call) RunAndReturn(run func() ([]models.Metrics, error)) *MockCollector_ExtendedMetricSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// MetricsSnapshot provides a mock function for the type MockCollector
func (_mock *MockCollector) MetricsSnapshot(counter int64) []models.Metrics {
	ret := _mock.Called(counter)

	if len(ret) == 0 {
		panic("no return value specified for MetricsSnapshot")
	}

	var r0 []models.Metrics
	if returnFunc, ok := ret.Get(0).(func(int64) []models.Metrics); ok {
		r0 = returnFunc(counter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}
	return r0
}

// MockCollector_MetricsSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MetricsSnapshot'
type MockCollector_MetricsSnapshot_Call struct {
	*mock.Call
}

// MetricsSnapshot is a helper method to define mock.On call
//   - counter int64
func (_e *MockCollector_Expecter) MetricsSnapshot(counter any) *MockCollector_MetricsSnapshot_Call {
	return &MockCollector_MetricsSnapshot_Call{Call: _e.mock.On("MetricsSnapshot", counter)}
}

func (_c *MockCollector_MetricsSnapshot_Call) Run(run func(counter int64)) *MockCollector_MetricsSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollector_MetricsSnapshot_Call) Return(metricss []models.Metrics) *MockCollector_MetricsSnapshot_Call {
	_c.Call.Return(metricss)
	return _c
}

func (_c *MockCollector_MetricsSnapshot_Call) RunAndReturn(run func(counter int64) []models.Metrics) *MockCollector_MetricsSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
