// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bazueva/metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSenderRepository creates a new instance of MockSenderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSenderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSenderRepository {
	mock := &MockSenderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSenderRepository is an autogenerated mock type for the SenderRepository type
type MockSenderRepository struct {
	mock.Mock
}

type MockSenderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSenderRepository) EXPECT() *MockSenderRepository_Expecter {
	return &MockSenderRepository_Expecter{mock: &_m.Mock}
}

// SendBatchMetric provides a mock function for the type MockSenderRepository
func (_mock *MockSenderRepository) SendBatchMetric(metrics []models.Metrics) error {
	ret := _mock.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for SendBatchMetric")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.Metrics) error); ok {
		r0 = returnFunc(metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSenderRepository_SendBatchMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatchMetric'
type MockSenderRepository_SendBatchMetric_Call struct {
	*mock.Call
}

// SendBatchMetric is a helper method to define mock.On call
//   - metrics []models.Metrics
func (_e *MockSenderRepository_Expecter) SendBatchMetric(metrics any) *MockSenderRepository_SendBatchMetric_Call {
	return &MockSenderRepository_SendBatchMetric_Call{Call: _e.mock.On("SendBatchMetric", metrics)}
}

func (_c *MockSenderRepository_SendBatchMetric_Call) Run(run func(metrics []models.Metrics)) *MockSenderRepository_SendBatchMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.Metrics
		if args[0] != nil {
			arg0 = args[0].([]models.Metrics)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSenderRepository_SendBatchMetric_Call) Return(err error) *MockSenderRepository_SendBatchMetric_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSenderRepository_SendBatchMetric_Call) RunAndReturn(run func(metrics []models.Metrics) error) *MockSenderRepository_SendBatchMetric_Call {
	_c.Call.Return(run)
	return _c
}
